'use strict';
const money = prompt('Ваш месячный доход?', 160000);
console.log(typeof money);
const  income = '15000';
console.log(typeof income);
const  addExpenses = prompt('Перечислите возможные расходы за рассчитываемый период через запятую');
console.log(addExpenses.length);
const deposit = confirm('Есть ли у вас депозит в банке?');
 console.log(typeof deposit);
const mission = 500000;
const period = 5;
console.log('Период равен '  + period + ' месяцев ' + 'Цель заработать ' + mission + ' рублей');
console.log(addExpenses.toLowerCase().split(', '));
const expenses1 = prompt('Введите обязательную статью расходов?');
const amount1 = +prompt('Во сколько это обойдется?', 40000);
const expenses2 = prompt('Введите обязательную статью расходов?');
const amount2 = +prompt('Во сколько это обойдется?', 20000);
const budgetMonth = amount1 + amount2;
console.log('Бюджет на месяц =', budgetMonth);
//const =
//console.log('Цель будет достигнута за ' +  + ' месяцев');
const budgetDay = budgetMonth / 30;
console.log('Бюджет на день =', budgetDay);