const money = 100000;
console.log(typeof money);
const  income = '15000';
console.log(typeof income);
const  addExpenses = 'iTunes, Apple Music, Food, Gym, Taxi';
console.log(addExpenses.length);
const deposit = true;
 console.log(typeof deposit);
const mission = 500000;
const period = 12;
console.log('Период равен '  + period + ' месяцев ' + 'Цель заработать ' + mission + ' рублей');
console.log(addExpenses.toLowerCase().split(', '));
const budgetDay = money / 30;
console.log('budgetDay =', budgetDay);